apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
      - name: driver-service
        image: driver-service:latest  # Ensure this matches the image you built
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

